{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentbay.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentbay.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets.data }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
